<?php

declare(strict_types=1);

namespace Slcorp\FileBundle\Infrastructure\Persistence\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251108134147 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(
            'CREATE TABLE file_bundle_files (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, contenthash VARCHAR(40) NOT NULL, pathnamehash VARCHAR(40) NOT NULL, contextid BIGINT NOT NULL, component VARCHAR(100) NOT NULL, filearea VARCHAR(50) NOT NULL, itemid BIGINT NOT NULL, filepath VARCHAR(255) NOT NULL, filename VARCHAR(255) NOT NULL, userid BIGINT DEFAULT NULL, filesize BIGINT NOT NULL, mimetype VARCHAR(100) DEFAULT NULL, status BIGINT NOT NULL, source TEXT DEFAULT NULL, author VARCHAR(255) DEFAULT NULL, license VARCHAR(255) DEFAULT NULL, timecreated BIGINT NOT NULL, timemodified BIGINT NOT NULL, sortorder BIGINT NOT NULL, referencefileid BIGINT DEFAULT NULL, PRIMARY KEY (id))'
        );
        $this->addSql('CREATE INDEX idx_contenthash ON file_bundle_files (contenthash)');
        $this->addSql('CREATE INDEX idx_pathnamehash ON file_bundle_files (pathnamehash)');
        $this->addSql('CREATE INDEX idx_context_component_filearea_itemid ON file_bundle_files (contextid, component, filearea, itemid)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE UNIQUE INDEX uniq_9bace7e1c74f2195 ON refresh_tokens (refresh_token)');
        $this->addSql('DROP TABLE file_bundle_files');
    }
}
